---
- name: "nxos.backup: fetch network configuration"
  nxos_config:
    backup: yes
  register: r_nxos_config

- name: "nxos.backup: remove non configuration lines"
  changed_when: false
  lineinfile:
    path: "{{ r_nxos_config.backup_path }}"
    regexp: "{{ item }}"
    state: absent
  loop:
    - '^(Current|Building) configuration.*'
    - '^\!.*'

- name: "nxos.backup: create folder structure"
  file:
    path: "{{ r_tempfile.path }}/{{ inventory_hostname }}/config"
    state: directory

- name: "nxos.backup: copy configuration to repo folder"
  copy:
    src: "{{ r_nxos_config.backup_path }}"
    dest: "{{ r_tempfile.path }}/{{ inventory_hostname }}/config/running.cfg"
    force: "yes"
  notify: git_sync
