---
- name: "backup"
  block:

    - name: "load nos/platform specific variables"
      include_vars: "{{ item }}"
      with_first_found:
        - skip: true
          files:
            - "{{ backup_manager_os }}/{{ backup_manager_platform }}/{{ backup_manager_version }}.yaml"
            - "{{ backup_manager_os }}/{{ backup_manager_platform }}.yaml"
            - "{{ backup_manager_os }}/main.yaml"
            - "main.yaml"
          paths: 
            - "../vars/"

    - name: "call pre tasks"
      include_tasks: "pre.yaml"

    - name: "call nos/platform specific tasks"
      include_tasks: "{{ item }}"
      with_first_found:
        - skip: true
          files:
            - "{{ backup_manager_os }}/{{ backup_manager_platform }}/{{ backup_manager_version }}/main.yaml"
            - "{{ backup_manager_os }}/{{ backup_manager_platform }}/main.yaml"
            - "{{ backup_manager_os }}/main.yaml"
  always:
    - name: "call post tasks"
      include_tasks: "post.yaml"
