---
- name: "load pre tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - skip: true
      files: "{{ firmware_mgmt_pre_tasks }}"

- name: "load pre roles"
  include_role: 
    name: "{{ item.name | default(item) }}"
    defaults_from: "{{ item.defaults_from | default(omit, True) }}"
    tasks_from: "{{ item.tasks_from | default(omit, True) }}"
    vars_from: "{{ item.vars_from | default(omit, True) }}"
  loop: "{{ firmware_mgmt_pre_roles }}"
